// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVR_ClJ_GZ6ExaaRBLDMP_NjKZSzYzCJY',
    appId: '1:478371157511:web:a4f5ebd23bd54e59e1bca2',
    messagingSenderId: '478371157511',
    projectId: 'exctinctx',
    authDomain: 'exctinctx.firebaseapp.com',
    storageBucket: 'exctinctx.appspot.com',
    measurementId: 'G-6E39JGNF87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfZTzmCaMQcpwkQGrWcxeyFQxtXWGaAas',
    appId: '1:478371157511:android:f4972f8b964d16dce1bca2',
    messagingSenderId: '478371157511',
    projectId: 'exctinctx',
    storageBucket: 'exctinctx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Pk_skI0qgwi4pWnEOejLcZl0280LuRo',
    appId: '1:478371157511:ios:845d84f95c9b5c57e1bca2',
    messagingSenderId: '478371157511',
    projectId: 'exctinctx',
    storageBucket: 'exctinctx.appspot.com',
    iosClientId: '478371157511-l7nkpps3lkr3h70d5hotjivrgn2r2tdf.apps.googleusercontent.com',
    iosBundleId: 'com.santiagoquihui.extinctx',
  );
}
